### ISSUE TITLE
not allowed to request upload slots

### ISSUE THREAD

**Issue by opensource93** [siacs/HttpUploadComponent#74] opened 2016-10-05 10:30 UTC
2016-10-05 06:27:55,447  DEBUG    Expire run finished in 0.000705s
2016-10-05 06:27:55,450  DEBUG    Loaded Plugin: XEP-0030: Service Discovery
2016-10-05 06:27:55,451  DEBUG    Loaded Plugin: upload files via http
2016-10-05 06:27:55,451  DEBUG    Connecting to localhost:5275
2016-10-05 06:27:55,451  DEBUG    DNS: Querying localhost for AAAA records.
2016-10-05 06:27:55,452  DEBUG    DNS: Querying localhost for A records.
2016-10-05 06:27:55,452  DEBUG    Connecting to [::1]:5275
2016-10-05 06:27:55,452  DEBUG    Event triggered: connected
2016-10-05 06:27:55,452  DEBUG     ==== TRANSITION disconnected -> connected
2016-10-05 06:27:55,453  DEBUG    Starting HANDLER THREAD
2016-10-05 06:27:55,453  DEBUG    Loading event runner
2016-10-05 06:27:55,453  DEBUG    SEND (IMMED): <stream:stream xmlns="jabber:component:accept" xmlns:stream="http://etherx.jabber.org/streams" to='upload.chat.intellibit.it'>
connected
2016-10-05 06:27:55,455  DEBUG    RECV: <stream:stream from="upload.chat.intellibit.it" id="e13ri6sc3">
2016-10-05 06:27:55,455  DEBUG    SEND (IMMED): <handshake xmlns="jabber:component:accept">97225e8737c394e60d7462033f24f2a5475a9c1d</handshake>
2016-10-05 06:27:55,456  DEBUG    RECV: <handshake />
2016-10-05 06:27:55,457  DEBUG    Event triggered: session_bind
2016-10-05 06:27:55,457  DEBUG    Event triggered: session_start
2016-10-05 06:27:55,495  DEBUG    RECV: <iq from="component.MYDOMAIN.TLD" type="get" to="upload.chat.intellibit.it" id="521-5470"><query xmlns="http://jabber.org/protocol/disco#info" /></iq>
2016-10-05 06:27:55,495  DEBUG    Received disco info query from <component.chat.intellibit.it> to <upload.chat.intellibit.it>.
2016-10-05 06:27:55,496  DEBUG    SEND: <iq from="upload.MYDOMAIN.TLD" type="result" to="component.chat.intellibit.it" id="521-5470"><query xmlns="http://jabber.org/protocol/disco#info"><feature var="urn:xmpp:http:upload" /><identity category="store" type="file" name="HTTP File Upload" /></query></iq>
2016-10-05 06:28:06,243  DEBUG    RECV: <iq from="MYUSER@MYDOMAIN.TLD/phone" type="get" to="upload.MYDOMAIN.TLD" id="n8s0sejq3q"><request xmlns="urn:xmpp:http:upload"><filename>IMG-20161004-WA0077.jpg</filename><size>50568</size><content-type>image/jpeg</content-type></request></iq>
2016-10-05 06:28:06,243  DEBUG    Event triggered: request_upload_slot
2016-10-05 06:28:06,244  DEBUG    SEND: <iq from="upload.MYDOMAIN.TLD" type="error" to="MYUSER@MYDOMAIN.TLD/phone" id="n8s0sejq3q"><error xmlns="jabber:client" type="cancel"><not-allowed xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">not allowed to request upload slots</text></error></iq>

**Comment by opensource93** [comment] 2016-10-06 10:22
Someone can help me?

**Comment by iNPUTmice** [comment] 2016-10-06 10:25
duplicate of #73

**Closed by iNPUTmice** 2016-10-06 10:25 UTC
